language: python
python:
  - "3.6"
install:
  - sudo apt-get install latexmk texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra
  - pip3 install poetry
  - poetry install
script:
  - make html latexpdf
